name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2'
          gleam-version: '1.14.0'
          rebar3-version: '3.24.0'
      - run: gleam run -m lustre/dev build app || gleam run -m lustre/dev build lustre_graph_generator
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
